# name: Linters

# on:
#   push:
#     branches: [main]
#   pull_request:

# jobs:
#   eslint:
#     name: ESLint
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v3

#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18.x'

#       - name: Install dependencies
#         run: npm ci

#       - name: Check ESLint version
#         run: npx eslint --version

#       - name: Run ESLint (ESM)
#         run: npx --node-arg="--experimental-specifier-resolution=node" eslint ./src --ext .js,.jsx --max-warnings=0 --config eslint.config.js



#   stylelint:
#     name: Stylelint
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v3

#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18.x'

#       - name: Install dependencies
#         run: npm ci --legacy-peer-deps

#       - name: Check Stylelint version
#         run: npx stylelint --version

#       - name: Run Stylelint
#         run: npx stylelint './src/**/*.{css,scss}'


name: Linters

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Run ESLint and Stylelint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (ESM config)
        run: |
          node --experimental-specifier-resolution=node node_modules/eslint/lib/cli.js \
          ./src --ext .js,.jsx --max-warnings=0 --config eslint.config.js

      - name: Run Stylelint
        run: npx stylelint './src/**/*.{css,scss}' --max-warnings=0
